# docker-compose.yml CORREGIDO
services:
  db:
    image: postgres:18
    container_name: osm-postgres
    restart: always
    environment:
      POSTGRES_USER: osm_user
      POSTGRES_PASSWORD: osm12345
      POSTGRES_DB: osm_analysis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: osm-api
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: