services:
  # Servicio 1: La API de FastAPI
  - type: web
    name: osm-api
    env: docker
    healthCheckPath: /
    envVars:
      - key: DB_HOST
        value: aws-1-us-east-1.pooler.supabase.com
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres.rchcovegcjwellhgaufv
      - key: DB_PASSWORD
        sync: false
      - key: MI_USUARIO
        sync: false
      - key: MI_CONTRASENA
        sync: false

  # Servicio 2: La Tarea Programada (Cron Job)
  # Este guion (-) debe estar exactamente alineado con el guion de arriba.
  - type: cron
    name: osm-scraper
    env: docker
    schedule: "5 4 * * *"
    command: "python run_update.py"